#!/usr/bin/dumb-init /bin/bash
set -euo pipefail

MYSQL_DB=${MY_DB:-clickyab}

MYSQLW_USER=${MYW_USER:-clickyab_master}
MYSQLW_PASSWORD=${MYW_PASS:-oRgLsGydHQnZzvdNfHM6}
MYSQLW_HOST=${MYW_HOST:-192.168.100.11}
MYSQLW_PORT=${MYW_PORT:-3306}

MYSQLR_USER=${MYR_USER:-clickyab_readonly}
MYSQLR_PASSWORD=${MYR_PASS:-gX^Zmp90jOJp91\$GwPujOTl2POQdlI}
MYSQLR_HOST=${MYR_HOST:-192.168.100.40}
MYSQLR_PORT=${MYR_PORT:-3306}

REDIS_HOST=${REDIS_HOST:-192.168.100.30}
REDIS_PORT=${REDIS_PORT:-2222}
RABBIT_PASS=${AMQP_PASS:-eeTheej2}
RABBIT_USER=${AMQP_USER:-cy}
RABBIT_HOST=${AMQP_HOST:-192.168.100.30}
RABBIT_PORT=${AMQP_POST:-5672}

# TODO : env re-write must be done here
export GAD_DEVEL_MODE=false
export GAD_CLICKYAB_UNDER_FLOOR=true
export GAD_SITE=a.clickyab.com
export GAD_PROTO=http
export GAD_REDIS_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
export GAD_REDIS_PASSWORD=${REDIS_PASSWORD:-bita123}
export GAD_REDIS_DATABASE=${REDIS_DATABASE:-7}
export GAD_REDIS_SIZE=${REDIS_SIZE:-250}
export GAD_MYSQL_MAX_CONNECTION=${MYSQL_MAX_CONNECTION:-250}
export GAD_MYSQL_MAX_CONNECTION=${MYSQL_MAX_IDLE_CONNECTION:-30}
export GAD_MYSQL_RDSN="${MYSQLR_USER}:${MYSQLR_PASSWORD}@tcp(${MYSQLR_HOST}:${MYSQLR_PORT})/${MYSQL_DB}?parseTime=true&charset=utf8"
export GAD_MYSQL_WDSN="${MYSQLW_USER}:${MYSQLW_PASSWORD}@tcp(${MYSQLW_HOST}:${MYSQLW_PORT})/${MYSQL_DB}?parseTime=true&charset=utf8"
export GAD_MYSQL_DATABASE="${MYSQL_DB}"
export GAD_PROFILE=disable
export GAD_AMQP_DSN="amqp://${RABBIT_USER}:${RABBIT_PASS}@${RABBIT_HOST}:${RABBIT_PORT}/"
export GAD_SLACK_ACTIVE=true
export GAD_PHP_CODE_ROOT=/app/clickyab-server/a/
export GAD_PHP_CODE_FPM=127.0.0.1:9000

if [ "$1" = '/app/bin/server' ];
then
	exec "$@"
else
	exec "$@"
fi;