// Code generated by lessc. DO NOT EDIT.
// Source: /routes/native_style.less

package routes

const style=`
.cyb-holder {
  direction: rtl;
  box-sizing: border-box;
  width: 100%;
  height: auto;
  font-size: 12pt;
  line-height: 1.4em;
  text-align: right;
  text-rendering: optimizeLegibility;
}
.cyb-holder .cyb-zero {
  height: 0 !important;
  margin: 0 !important;
  padding: 0 !important;
}
.cyb-holder .cyb-none {
  display: none;
  visibility: hidden;
}
.cyb-holder .cyb-title-holder {
  display: flex;
}
.cyb-holder .cyb-title-holder .cyb-title-after {
  flex: 1;
}
.cyb-holder .cyb-title-holder .cyb-title-after {
  margin: .7em 0;
}
.cyb-holder .cyb-title-holder .cyb-title {
  color: inherit;
  padding: 10px;
  font-size: inherit;
  font-weight: bold;
}
.cyb-holder .cyb-title-holder .cyb-logo {
  overflow: hidden;
  position: relative;
  padding: 10px;
}
.cyb-holder .cyb-title-holder .cyb-logo a:hover {
  color: #44B6E7;
}
.cyb-holder .cyb-title-holder .cyb-logo .cyb-logo-container img {
  float: left;
  padding-right: 5px;
  -webkit-filter: grayscale(100%);
  /* Safari 6.0 - 9.0 */
  filter: grayscale(100%);
}
.cyb-holder .cyb-title-holder .cyb-logo .cyb-logo-container:hover img {
  -webkit-filter: none;
  /* Safari 6.0 - 9.0 */
  filter: none;
}
.cyb-holder .cyb-suggests {
  display: flex;
  flex-wrap: wrap-reverse;
}
.cyb-holder .cyb-suggests .cyb-pack {
  display: flex;
  flex: 1;
  flex-wrap: wrap-reverse;
  min-width: 141px;
  flex-basis: 282px;
}
.cyb-holder .cyb-suggests .cyb-pack.cyb-min-size {
  min-width: cyb-minSize;
  flex-basis: cyb-doubleMinSize;
}
.cyb-holder .cyb-suggests.cyb-left .cyb-suggest {
  font-size: .9em;
  flex-basis: 141px;
  flex-direction: row;
}
.cyb-holder .cyb-suggests.cyb-left .cyb-suggest .cyb-img-holder,
.cyb-holder .cyb-suggests.cyb-left .cyb-suggest .cyb-desc-holder {
  flex: 1;
}
.cyb-holder .cyb-suggests.cyb-left .cyb-suggest .cyb-img-holder {
  flex-grow: 2;
  padding-top: 6px;
}
.cyb-holder .cyb-suggests.cyb-left .cyb-suggest .cyb-desc-holder {
  flex-grow: 3;
  padding: 0 5px;
}
.cyb-holder .cyb-suggests.cyb-right .cyb-suggest {
  font-size: .9em;
  flex-basis: 141px;
  margin: 5px;
  flex-direction: row-reverse;
}
.cyb-holder .cyb-suggests.cyb-right .cyb-suggest .cyb-img-holder,
.cyb-holder .cyb-suggests.cyb-right .cyb-suggest .cyb-desc-holder {
  flex: 1;
}
.cyb-holder .cyb-suggests.cyb-right .cyb-suggest .cyb-img-holder {
  flex-grow: 2;
  padding-top: 6px;
}
.cyb-holder .cyb-suggests.cyb-right .cyb-suggest .cyb-desc-holder {
  flex-grow: 3;
  padding: 0 5px;
}
.cyb-holder .cyb-suggests.cyb-top .cyb-suggest {
  flex-direction: column;
}
.cyb-holder .cyb-suggests.cyb-top .cyb-suggest .cyb-img-holder,
.cyb-holder .cyb-suggests.cyb-top .cyb-suggest .cyb-desc-holder {
  flex: 1;
  margin: 4px;
}
.cyb-holder .cyb-suggests.cyb-top .cyb-suggest .cyb-desc-holder {
  margin-bottom: 10px;
}
.cyb-holder .cyb-suggests.cyb-top .cyb-suggest .cyb-desc-holder {
  font-size: 1em;
}
.cyb-holder .cyb-suggests.cyb-bottom .cyb-suggest {
  margin: 5px;
  flex-direction: column-reverse;
}
.cyb-holder .cyb-suggests.cyb-bottom .cyb-suggest .cyb-img-holder,
.cyb-holder .cyb-suggests.cyb-bottom .cyb-suggest .cyb-desc-holder {
  flex: 1;
  margin: 4px;
}
.cyb-holder .cyb-suggests.cyb-bottom .cyb-suggest .cyb-desc-holder {
  margin-bottom: 10px;
}
.cyb-holder .cyb-suggests .cyb-suggest {
  display: flex;
  flex: 1;
  margin-bottom: 15px;
  position: relative;
  flex-basis: 144px;
}
.cyb-holder .cyb-suggests .cyb-suggest .cyb-img-holder .cyb-img {
  width: 100%;
  height: auto;
}
.cyb-holder .cyb-suggests .cyb-suggest .cyb-img-holder .cyb-img.cyb-round {
  border-radius: 5px;
}
.cyb-holder .cyb-suggests .cyb-more {
  border-radius: 1em;
  border: .1em solid;
  /* background: green; */
  border-color: rgba(128, 128, 128, 0.4);
  padding: 6px 13px;
  display: inline;
  font-size: 0.7em;
}
.cyb-holder a {
  color: inherit;
  text-decoration: none;
  display: block;
}
.cyb-holder.cyb-side .cyb-suggests .cyb-pack {
  flex-basis: 100%;
}
.cyb-holder.cyb-side .cyb-suggests .cyb-pack .cyb-suggest {
  flex-basis: 100%;
}
.cyb-vertical .cyb-img-holder,
.cyb-vertical .cyb-desc-holder {
  flex: 1;
  margin: 4px;
}
.cyb-vertical .cyb-desc-holder {
  margin-bottom: 10px;
}
.cyb-horizontal {
  font-size: .9em;
  flex-basis: 141px;
}
.cyb-horizontal .cyb-img-holder,
.cyb-horizontal .cyb-desc-holder {
  flex: 1;
}
.cyb-horizontal .cyb-img-holder {
  flex-grow: 2;
  padding-top: 6px;
}
.cyb-horizontal .cyb-desc-holder {
  flex-grow: 3;
  padding: 0 5px;
}
`
