---
# prepare docker and images for webservers:
- name: build the code
  hosts: vagrant

  tasks:
    - name: clean all data
      make:
        target: clean
        chdir: /home/develop/gad

    - name: build binaries
      make:
        target: all
        chdir: /home/develop/gad

# copy builded go app to webservers:
- name: copy builded GO app to webservers and run
  hosts: staging
  tasks:

    - name: make sure docker.py is ready
      pip:
        name: docker-py

    - name: Creates directory
      file:
        path: /home/cy/gad
        state: directory


    - name: pull ubuntu image
      docker_image:
        name: registry.clickyab.ae/clickyab/ubuntu

    - name: sync the runner image
      synchronize:
        src: "{{ playbook_dir }}/docker-runner/"
        dest: /home/cy/gad/docker-runner
        delete: yes
        checksum: yes
        times: no

    - name: build the docker
      docker_image:
        path: /home/cy/gad/docker-runner
        name: registry.clickyab.ae/clickyab/gad-runner


    - name: copy go binary files to web servers
      synchronize:
        src: "{{ playbook_dir }}/../../bin/"
        dest: "/home/cy/gad/bin/"
        delete: yes
        rsync_opts: "--exclude=.git --exclude=*.sh --exclude=gb* --exclude=go-bindata --exclude=fswatch --exclude=codegen --exclude=.gitignore"
        checksum: yes
        times: no


    - name: sync the clcikyab-old code
      synchronize:
        src: "{{ playbook_dir }}/../../clickyab-server/"
        dest: "/home/cy/gad/clickyab-server/"
        delete: yes
        rsync_opts: "--exclude=.git --exclude=gb* --exclude=go-bindata --exclude=fswatch --exclude=codegen --exclude=.gitignore"
        checksum: yes
        times: no

- name: Run click worker
  hosts: click
  tasks:

    - name: Re-create a click container
      docker_container:
        name: gad-click
        image: registry.clickyab.ae/clickyab/gad-runner
        command: /app/bin/clickworker
        state: started
        restart_policy: always
        recreate: yes
        volumes:
          - /home/cy/gad:/app
        env:
          GAD_AMQP_DEBUG: "{{ amqp_debug }}"
          
- name: Run imp worker
  hosts: imp
  tasks:

    - name: Re-create a imp worker
      docker_container:
        name: gad-imp
        image: registry.clickyab.ae/clickyab/gad-runner
        command: /app/bin/impworker
        state: started
        restart_policy: always
        recreate: yes
        volumes:
          - /home/cy/gad:/app
        env:
          GAD_AMQP_DEBUG: "{{ amqp_debug }}"

- name: Run conv worker
  hosts: conv
  tasks:

    - name: Re-create conv worker
      docker_container:
        name: gad-conv
        image: registry.clickyab.ae/clickyab/gad-runner
        command: /app/bin/convworker
        state: started
        restart_policy: always
        recreate: yes
        volumes:
          - /home/cy/gad:/app
        env:
          GAD_AMQP_DEBUG: "{{ amqp_debug }}"

- name: Run web server
  hosts: web
  tasks:

    # - name: stop the nginx
    #   docker_container:
    #     name: nginx
    #     state: stopped

    - name: Re-create a web container
      docker_container:
        name: gad-web
        image: registry.clickyab.ae/clickyab/gad-runner
        command: /app/bin/server
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "{{ gad_port }}:80"
        volumes:
          - /home/cy/gad:/app
        env:
          GAD_AMQP_DEBUG: "{{ amqp_debug }}"          