package mr

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"time"
)

type PooyaArray []int64

type AdAttributes struct {
	LinkTextType                    string `json:"link_text_type"`
	BannerTitleTextType             string `json:"banner_title_text_type"`
	TemplateID                      string `json:"template_id"`
	CtaTitleTextType                string `json:"cta_title_text_type"`
	Logo                            string `json:"logo"`
	Product                         string `json:"product"`
	BannerDescriptionTextType       string `json:"banner_description_text_type"`
	PriceTextType                   string `json:"price_text_type"`
	OffPriceTextType                string `json:"off_price_text_type"`
	BackgroundBannerPickerSelector  string `json:"background_banner_picker_selector"`
	CtaBannerPickerSelector         string `json:"cta_banner_picker_selector"`
	TitleBannerPickerSelector       string `json:"title_banner_picker_selector"`
	DescriptionBannerPickerSelector string `json:"description_banner_picker_selector"`
	IconCtaBannerPickerSelector     string `json:"icon_cta_banner_picker_selector"`
	TextCtaBannerPickerSelector     string `json:"text_cta_banner_picker_selector"`
	OffPriceBannerPickerSelector    string `json:"off_price_banner_picker_selector"`
	LivePriceBannerPickerSelector   string `json:"live_price_banner_picker_selector"`
}

type AutoGenerated []struct {
	AdID              int64          `json:"ad_id"`
	AdSize            int            `json:"ad_size"`
	UserID            int64          `json:"u_id"`
	AdName            sql.NullString `json:"ad_name"`
	AdURL             sql.NullString `json:"ad_url"`
	AdCode            sql.NullString `json:"ad_code"`
	AdTitle           sql.NullString `json:"ad_title"`
	AdBody            sql.NullString `json:"ad_body"`
	AdImg             sql.NullString `json:"ad_img"`
	AdStatus          int            `json:"ad_status"`
	AdRejectReason    sql.NullString `json:"ad_reject_reason"`
	AdCtr             float64        `json:"ad_ctr"`
	AdConv            int            `json:"ad_conv"`
	AdTime            int            `json:"ad_time"`
	AdType            int            `json:"ad_type"`
	AdMainText        sql.NullString `json:"ad_mainText"`
	AdDefineText      sql.NullString `json:"ad_defineText"`
	AdTextColor       sql.NullString `json:"ad_textColor"`
	AdTarget          sql.NullString `json:"ad_target"`
	AdAttribute       AdAttributes   `json:"ad_attribute"`
	AdHashAttribute   string         `json:"ad_hash_attribute"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	UEmail            string         `json:"u_email"`
	UBalance          string         `json:"u_balance"`
	CpID              int64          `json:"cp_id"`
	CpType            int            `json:"cp_type"`
	CpBillingType     sql.NullString `json:"cp_billing_type"`
	CpName            sql.NullString `json:"cp_name"`
	CpNetwork         int            `json:"cp_network"`
	CpPlacement       PooyaArray     `json:"cp_placement"`
	CpWfilter         PooyaArray     `json:"cp_wfilter"`
	CpRetargeting     sql.NullString `json:"cp_retargeting"`
	CpFrequency       int            `json:"cp_frequency"`
	CpSegmentID       sql.NullInt64  `json:"cp_segment_id"`
	CpAppBrand        sql.NullString `json:"cp_app_brand"`
	CpNetProvider     sql.NullString `json:"cp_net_provider"`
	CpAppLang         sql.NullString `json:"cp_app_lang"`
	CpAppMarket       sql.NullInt64  `json:"cp_app_market"`
	CpWebMobile       int            `json:"cp_web_mobile"`
	CpWeb             int            `json:"cp_web"`
	CpApplication     int            `json:"cp_application"`
	CpVideo           int            `json:"cp_video"`
	CpAppsCarriers    sql.NullString `json:"cp_apps_carriers"`
	CpLongmap         sql.NullString `json:"cp_longmap"`
	CpLatmap          sql.NullString `json:"cp_latmap"`
	CpRadius          int            `json:"cp_radius"`
	CpOptCtr          int            `json:"cp_opt_ctr"`
	CpOptConv         int            `json:"cp_opt_conv"`
	CpOptBr           int            `json:"cp_opt_br"`
	CpGender          int            `json:"cp_gender"`
	CpAlexa           int            `json:"cp_alexa"`
	CpFatfinger       int            `json:"cp_fatfinger"`
	CpUnder           int            `json:"cp_under"`
	CpGeos            PooyaArray     `json:"cp_geos"`
	CpRegion          PooyaArray     `json:"cp_region"`
	CpCountry         PooyaArray     `json:"cp_country"`
	CpHoods           PooyaArray     `json:"cp_hoods"`
	CpIspBlacklist    PooyaArray     `json:"cp_isp_blacklist"`
	CpCat             PooyaArray     `json:"cp_cat"`
	CpLikeApp         PooyaArray     `json:"cp_like_app"`
	CpApp             PooyaArray     `json:"cp_app"`
	CpAppFilter       PooyaArray     `json:"cp_app_filter"`
	CpKeywords        PooyaArray     `json:"cp_keywords"`
	CpPlatforms       PooyaArray     `json:"cp_platforms"`
	CpPlatformVersion PooyaArray     `json:"cp_platform_version"`
	CpMaxbid          int            `json:"cp_maxbid"`
	CpWeeklyBudget    int            `json:"cp_weekly_budget"`
	CpDailyBudget     int            `json:"cp_daily_budget"`
	CpTotalBudget     int            `json:"cp_total_budget"`
	CpWeeklySpend     int            `json:"cp_weekly_spend"`
	CpTotalSpend      int            `json:"cp_total_spend"`
	CpTodaySpend      int            `json:"cp_today_spend"`
	CpClicks          int            `json:"cp_clicks"`
	CpCtr             float64        `json:"cp_ctr"`
	CpImps            int            `json:"cp_imps"`
	CpCpm             int            `json:"cp_cpm"`
	CpCpa             int            `json:"cp_cpa"`
	CpCpc             int            `json:"cp_cpc"`
	CpConv            int            `json:"cp_conv"`
	CpConvRate        float64        `json:"cp_conv_rate"`
	CpRevenue         int            `json:"cp_revenue"`
	CpRoi             int            `json:"cp_roi"`
	CpStart           int            `json:"cp_start"`
	CpEnd             int            `json:"cp_end"`
	CpStatus          int            `json:"cp_status"`
	CpLastupdate      int            `json:"cp_lastupdate"`
	CpHourStart       int            `json:"cp_hour_start"`
	CpHourEnd         int            `json:"cp_hour_end"`
	IsCrm             int            `json:"is_crm"`
	CpLock            int            `json:"cp_lock"`
	CPCreatedAt       time.Time      `json:"created_at"`
	CPUpdatedAt       time.Time      `json:"updated_at"`
}

// Scan convert the json array ino string slice
func (gjf *AdAttributes) Scan(src interface{}) error {
	var b []byte
	switch src.(type) {
	case []byte:
		b = src.([]byte)
	case string:
		b = []byte(src.(string))
	case nil:
		b = make([]byte, 0)
	default:
		return errors.New("unsupported type")
	}

	_ = json.Unmarshal(b, gjf)
	return nil
}

// Value try to get the string slice representation in database
func (gjf AdAttributes) Value() (driver.Value, error) {
	return json.Marshal(gjf)
}
